tap "homebrew/bundle"
tap "homebrew/core"
brew "aws-okta"
brew "ghc"
brew "grep"
brew "haskell-stack"
brew "jq"
brew "mackup"
brew "node"
brew "openssl@3"
brew "terraform", link: false
brew "tfenv"
brew "tree"
brew "wget"
